// ============================================================
// PLANIT — Core Type Definitions
// ============================================================

// ----- User & Memory ----------------------------------------

export interface UserProfile {
  id: string;
  name: string;
  email: string;
  avatar_url?: string;
  persona?: string;
  memory_vector?: number[];
  created_at: string;
  updated_at: string;
}

export type AllergySeverity = "mild" | "moderate" | "severe" | "fatal";

export interface AccessibilityPreferences {
  id: string;
  user_id: string;
  // Mobility
  uses_wheelchair: boolean;
  uses_cane: boolean;
  requires_elevator: boolean;
  requires_ramp: boolean;
  limited_walking_distance_meters?: number;
  // Vision
  low_vision: boolean;
  blind: boolean;
  // Hearing
  hard_of_hearing: boolean;
  deaf: boolean;
  // Sensory
  low_sensory: boolean; // prefers quiet, low-stimulation environments
  light_sensitivity: boolean;
  // Dietary
  dietary_restrictions: DietaryRestriction[];
  allergies: Allergy[];
  // Preferences
  preferred_transport: TransportMode[];
  avoided_environments: string[]; // e.g. "crowded", "loud", "dim_lighting"
  created_at: string;
  updated_at: string;
}

export interface DietaryRestriction {
  type: "vegan" | "vegetarian" | "halal" | "kosher" | "gluten_free" | "dairy_free" | "custom";
  label: string;
}

export interface Allergy {
  item: string; // e.g. "shellfish", "peanuts", "latex"
  severity: AllergySeverity;
}

export interface UserMemory {
  id: string;
  user_id: string;
  category: MemoryCategory;
  key: string;
  value: string;
  embedding?: number[];
  source: "voice" | "text" | "inferred" | "feedback";
  confidence: number; // 0-1
  created_at: string;
  updated_at: string;
}

export type MemoryCategory =
  | "likes"
  | "dislikes"
  | "allergies"
  | "accessibility"
  | "budget"
  | "vibe"
  | "transport"
  | "accommodation"
  | "activity"
  | "custom";

// ----- Itinerary & Branching --------------------------------

export type NodeType =
  | "activity"
  | "meal"
  | "transport"
  | "accommodation"
  | "event"
  | "rest"
  | "pivot";

export type BudgetTier = "budget" | "mid-range" | "premium" | "luxury";

export interface GeoLocation {
  lat: number;
  lng: number;
  address: string;
  place_id?: string;
}

export interface BookingLink {
  platform: string; // "Expedia", "OpenTable", "Uber", "Booking.com"
  url: string;
  label: string; // "Book on Expedia", "Reserve on OpenTable"
  category: "hotel" | "restaurant" | "transport" | "activity" | "event";
  price_indicator?: string; // "$45", "Free", "From ¥3,200"
}

export interface TransportOption {
  mode: TransportMode;
  label: string; // "Oedo Line via Shinjuku"
  duration_minutes: number;
  cost_estimate?: string;
  accessibility_note?: string; // "Use Exit A1 for elevator"
  booking_link?: BookingLink;
  tags: TransportTag[];
  steps?: string[];
}

export type TransportMode =
  | "walk"
  | "train"
  | "bus"
  | "taxi"
  | "uber"
  | "bike"
  | "subway"
  | "tram"
  | "ferry"
  | "car_rental";

export type TransportTag = "fastest" | "cheapest" | "most_accessible" | "eco" | "scenic";

export interface ItineraryNode {
  id: string;
  itinerary_id: string;
  parent_id?: string; // null = root node
  branch_label?: string; // "A", "B", "C" or "Primary", "Foodie Path", "Shopping Path"
  type: NodeType;
  title: string;
  description: string;
  location: GeoLocation;
  start_time: string; // ISO 8601
  end_time: string;
  duration_minutes: number;
  budget_tier: BudgetTier;
  budget_estimate?: string; // "¥2,500" or "$30"
  why_selected: string; // "Selected because it's a Low-Sensory zone with elevator access"
  tags: string[];
  accessibility_verified: boolean;
  accessibility_notes?: string;
  booking_links: BookingLink[];
  transport_options?: TransportOption[];
  // Rich details
  phone?: string;
  website?: string;
  opening_hours?: string;
  rating?: number;
  review_count?: number;
  image_url?: string;
  atmosphere?: string[]; // ["quiet", "historic", "indoor"]
  is_active: boolean; // Is this the currently selected branch?
  is_pivot?: boolean; // Was this auto-generated by the Proactive Pivot?
  metadata?: Record<string, unknown>;
  created_at: string;
}

export interface ItineraryBranch {
  id: string;
  parent_node_id: string;
  label: string; // "B", "Shopping Path"
  theme: string; // "Foodie", "Shopping", "Relax"
  nodes: ItineraryNode[];
  is_active: boolean;
}

export interface Itinerary {
  id: string;
  user_id: string;
  title: string;
  destination: string;
  start_date: string;
  end_date: string;
  budget_tier: BudgetTier;
  budget_total_estimate?: string;
  status: "draft" | "active" | "completed" | "pivoted";
  timezone?: string; // IANA timezone, e.g. "Asia/Tokyo" — used for correct local-time display
  nodes: ItineraryNode[];
  branches: ItineraryBranch[];
  accessibility_summary?: string;
  pivot_reason?: string;
  weather_context?: WeatherContext;
  created_at: string;
  updated_at: string;
}

// ----- Context & State -------------------------------------

export interface WeatherContext {
  condition: "sunny" | "cloudy" | "rainy" | "stormy" | "snowy" | "windy";
  temperature_celsius: number;
  description: string;
  icon?: string;
  timestamp: string;
}

export interface UserLocation {
  lat: number;
  lng: number;
  accuracy_meters?: number;
  city?: string;
  country?: string;
  timestamp: string;
}

// ----- LangGraph State -------------------------------------

export interface PlanitState {
  // User context
  user_id: string;
  user_profile?: UserProfile;
  accessibility_prefs?: AccessibilityPreferences;
  user_memories: UserMemory[];

  // Current location & time
  current_location?: UserLocation;
  current_time: string;

  // Weather
  weather?: WeatherContext;

  // Active itinerary
  itinerary?: Itinerary;
  active_node_id?: string;

  // Conversation
  messages: AgentMessage[];
  user_input?: string;
  voice_transcript?: string;

  // Agent routing
  intent?: PlanitIntent;
  requires_pivot: boolean;
  pivot_trigger?: "weather" | "location_deviation" | "user_request" | "time_overrun";

  // Tool results (intermediate)
  search_results?: SearchResult[];
  places_data?: PlaceData[];
  transport_options?: TransportOption[];

  // Output
  response?: string;
  itinerary_update?: Partial<Itinerary>;
  error?: string;
}

export type PlanitIntent =
  | "onboard"
  | "plan_day"
  | "get_commute"
  | "find_nearby"
  | "pivot_itinerary"
  | "update_memory"
  | "book_activity"
  | "general_chat";

export interface AgentMessage {
  role: "user" | "assistant" | "system" | "tool";
  content: string;
  timestamp: string;
  tool_call_id?: string;
  tool_name?: string;
}

// ----- Tool Results ----------------------------------------

export interface SearchResult {
  title: string;
  url: string;
  content: string;
  score?: number;
  published_date?: string;
}

export interface PlaceData {
  place_id: string;
  name: string;
  address: string;
  location: GeoLocation;
  type: string[];
  rating?: number;
  review_count?: number;
  price_level?: number; // 0-4
  opening_hours?: {
    open_now: boolean;
    periods?: Array<{ day: number; open: string; close: string }>;
    weekday_text?: string[];
  };
  phone?: string;
  website?: string;
  photos?: string[];
  atmosphere?: string[];
  accessibility?: {
    wheelchair_accessible_entrance: boolean;
    wheelchair_accessible_parking: boolean;
    wheelchair_accessible_restroom: boolean;
    elevator?: boolean;
  };
}

// ----- Interactions / Feedback Loop -------------------------

export interface Interaction {
  id: string;
  user_id: string;
  itinerary_id?: string;
  node_id?: string;
  type: "accept" | "reject" | "pivot" | "feedback" | "voice_command";
  content?: string; // e.g. "That hotel lounge was too dark"
  extracted_memory?: Partial<UserMemory>;
  created_at: string;
}

// ----- API Payloads ----------------------------------------

export interface ChatRequest {
  message: string;
  user_id: string;
  itinerary_id?: string;
  location?: UserLocation;
  voice_mode?: boolean;
}

export interface ChatResponse {
  response: string;
  itinerary_update?: Partial<Itinerary>;
  new_nodes?: ItineraryNode[];
  memory_updates?: Partial<UserMemory>[];
  transport_options?: TransportOption[];
  suggestions?: string[];
  trip_suggestions?: TripSuggestions;
  mode?: "chat" | "suggest";
}

// ============================================================
// Multi-Step Planning Flow Types
// ============================================================

export interface ActivitySuggestion {
  id: string;
  city: string;
  type: NodeType;
  title: string;
  description: string;
  location: GeoLocation;
  duration_minutes: number;
  budget_tier: BudgetTier;
  budget_estimate: string;
  tags: string[];
  why_selected: string;
  accessibility_verified: boolean;
  accessibility_notes?: string;
  booking_links: BookingLink[];
  image_url?: string;
  rating?: number;
  // Event-specific fields (only when is_event === true)
  is_event: boolean;
  event_date?: string;     // "2026-04-01" — fixed calendar date
  event_start?: string;    // "20:00" — fixed start time HH:MM
  event_end?: string;      // "22:30"
  ticket_links?: BookingLink[];
}

export interface CitySuggestions {
  city: string;
  date_range: { from: string; to: string };   // YYYY-MM-DD
  activities: ActivitySuggestion[];           // flexible — no fixed date
  events: ActivitySuggestion[];               // time-fixed events happening in date_range
}

export interface TripSuggestions {
  trip_title: string;
  destination: string;
  start_date: string;  // YYYY-MM-DD
  end_date: string;    // YYYY-MM-DD
  cities: CitySuggestions[];
}

export interface FoodSuggestion {
  id: string;
  city: string;
  title: string;
  description: string;
  location: GeoLocation;
  meal_type: "breakfast" | "lunch" | "dinner" | "snack";
  cuisine: string;
  must_try_dishes: string[];
  why_authentic: string;
  budget_tier: BudgetTier;
  budget_estimate: string;
  tags: string[];
  accessibility_verified: boolean;
  accessibility_notes?: string;
  booking_links: BookingLink[];
  rating?: number;
  tips?: string;
}

export interface ActivityConflict {
  date: string;        // "2026-04-03"
  time_slot: string;   // "20:00–21:30"
  options: ActivitySuggestion[];  // exactly 2 items
}

export interface PivotRequest {
  user_id: string;
  itinerary_id: string;
  trigger: PlanitState["pivot_trigger"];
  current_location: UserLocation;
  weather?: WeatherContext;
  context?: string;
}
